### ISSUE TITLE
Assalomalekum ustoz. Meni g'oyam  "Bot"da start tugmasi boslgandan keyin botda tilni tanlash deb 3 ta 4 tillar chiqsa boshqa millat vakillari tushuninishi uchun qulay bo'ladi. Til tanlangandan keyin foydalanuvchi locatsiyasi orqali  undagi ob xavo ko'rsatiladi. obxavo ilovalarida  3.4 kulik obxavo ko'rsatiladi siz xam shunday qilib botda ayni paytdagi vaqt keyngi kunlarda gi ob xavo malumotlari qo'ylsa yaxshi bo'ladi.  "Eng muxumi bot xabar yuborib, xabarni olgandan keyin o'zi yuborgan xabarni aftamatik ravishta o'chirsa juda yaxshi bo'ladi. "   Bu mening fikrim edi yani g'oyam.  "Hikmatov Bekzod"

### ISSUE THREAD

**Issue by BekzodHikmatov** [dostonnabotov/weather-scout#1]

**Comment by technoph1le** [comment]
- Tillarni ustida ishlayapman. Keyingi versiyalarda chiqadi.
- Foydalanuvchini joyini aniqlash biroz vaqt olyapti. Bir nechta usullardan sinab ko'rdim, lekin foydalanuvchi manzili emas, serverni manzilini ko'rsatyapti. Buni yana ko'rib chiqaman.
- Ertangi yoki undan keyingi ob-havo ma'lumotlari ustida ham ishlayapman, keyingi versiyalarda chiqadi.

G'oyalar uchun rahmat! 👍

**Comment by technoph1le** [comment]
- Bir hafta davomida ob havo haqida ma'umot `v1.4.0` ga qo'shildi. `/forecast` bilan.
